name: KMM, iOS, and macOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build for macOS
      run: swift build -v
    - name: Run tests for macOS
      run: swift test -v
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build Assessment Model
      run: ./gradlew :assessmentmodel:assembleKotlinModelDebugXCFramework
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme iosApp -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" | xcpretty
    - name: Run tests for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme iosApp -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" | xcpretty
